export { createSceneGeometry, nodeOrientationMatrix, projectedNode, viewportMatrix } from './scene'
export type { SceneGeometry } from './scene'
export { selectionPath, selectionHandleRect, rotationHandleLayout } from './selection'
export type { RotationHandleLayout } from './selection'
export type { RotationPreview, ViewportTransform } from './types'
export { gradientHandles, moveGradientHandle } from './gradient'
export type { GradientHandle, GradientHandles } from './gradient'
export { snapGradientPoint } from './gradient-snap'
export type { GradientSnapGuide, GradientSnapResult } from './gradient-snap'
