import { expect, test } from '@playwright/test'

import { createLayoutModeScene } from '#tests/helpers/layout-mode'
import { propertyField, propertySection } from '#tests/helpers/properties'

test('exclusion updates position, constraints and sizing immediately, with exact undo', async ({
  page
}) => {
  const scene = await createLayoutModeScene(page)
  const position = propertySection(page, 'Position')
  const constraints = propertySection(page, 'Constraints')
  const toggle = position.getByRole('switch', { name: 'Exclude from auto layout' })
  const x = propertyField(page, 'x')
  const y = propertyField(page, 'y')
  const align = position.getByRole('button', { name: 'Align left', exact: true })
  await expect(toggle).not.toBeChecked()
  await expect(x).toHaveAttribute('aria-disabled', 'true')
  await expect(y).toHaveAttribute('aria-disabled', 'true')
  await expect(align).toBeDisabled()
  await expect(constraints).toBeHidden()
  await page.getByRole('combobox', { name: 'Width', exact: true }).click()
  await expect(page.getByRole('option', { name: 'Fill', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  const before = await scene.read()
  await toggle.check()
  await expect(toggle).toBeChecked()
  await expect(x).not.toHaveAttribute('aria-disabled', 'true')
  await expect(y).not.toHaveAttribute('aria-disabled', 'true')
  await expect(align).toBeEnabled()
  await expect(constraints).toBeVisible()
  await page.getByRole('combobox', { name: 'Width', exact: true }).click()
  await expect(page.getByRole('option', { name: 'Fill', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  const after = await scene.read()
  await page.getByTestId('canvas-element').focus()
  await page.keyboard.press('Meta+z')
  await expect.poll(scene.read).toEqual(before)
  await expect(toggle).not.toBeChecked()
  await expect(x).toHaveAttribute('aria-disabled', 'true')
  await expect(constraints).toBeHidden()
  await page.keyboard.press('Meta+Shift+z')
  await expect.poll(scene.read).toEqual(after)
  await expect(constraints).toBeVisible()
  await x.dblclick()
  const input = position.getByRole('spinbutton', { name: 'X Axis', exact: true })
  await input.fill('75')
  await input.press('Enter')
  await expect
    .poll(async () => (await scene.read()).nodes.find((node) => node.id === scene.ids.frame)?.x)
    .toBe(75)
})

test('parent changes and mixed selections update controls without reselection', async ({
  page
}) => {
  const scene = await createLayoutModeScene(page)
  const toggle = page.getByRole('switch', { name: 'Exclude from auto layout' })
  const constraints = propertySection(page, 'Constraints')
  await scene.select([scene.ids.first])
  await expect(toggle).toBeHidden()
  await expect(constraints).toBeVisible()
  await scene.setLayoutMode(scene.ids.frame, 'VERTICAL')
  await expect(toggle).toBeVisible()
  await expect(constraints).toBeHidden()
  await toggle.check()
  await scene.select([scene.ids.first, scene.ids.second])
  await expect(toggle).toHaveAttribute('data-mixed')
  await expect(propertyField(page, 'x')).toHaveAttribute('aria-disabled', 'true')
  await expect(constraints).toBeHidden()
  const before = await scene.read()
  await toggle.click()
  await expect(toggle).toBeChecked()
  await expect(constraints).toBeVisible()
  await page.getByTestId('canvas-element').focus()
  await page.keyboard.press('Meta+z')
  await expect.poll(scene.read).toEqual(before)
  await expect(toggle).toHaveAttribute('data-mixed')
  await scene.select([scene.ids.first])
  await scene.setLayoutMode(scene.ids.frame, 'NONE')
  await expect(toggle).toBeHidden()
  await expect(propertyField(page, 'x')).not.toHaveAttribute('aria-disabled', 'true')
  await expect(constraints).toBeVisible()
  await scene.select([scene.ids.outer])
  await expect(toggle).toBeHidden()
  await expect(constraints).toBeHidden()
  await expect(propertyField(page, 'x')).not.toHaveAttribute('aria-disabled', 'true')
  await scene.setLayoutMode(scene.ids.frame, 'VERTICAL')
  await scene.select([scene.ids.first, scene.ids.outer])
  await expect(toggle).toBeHidden()
  await scene.select([scene.ids.first])
  await expect(toggle).toBeVisible()
})

test('both center constraint axes remain independently clickable', async ({ page }, testInfo) => {
  const scene = await createLayoutModeScene(page)
  await scene.select([scene.ids.first])
  const constraints = propertySection(page, 'Constraints')
  const horizontal = constraints.getByRole('button', { name: 'Horizontal center', exact: true })
  const vertical = constraints.getByRole('button', { name: 'Vertical center', exact: true })
  await horizontal.click()
  await expect(horizontal).toHaveAttribute('aria-pressed', 'true')
  await expect(vertical).toHaveAttribute('aria-pressed', 'false')
  await vertical.click()
  await expect(horizontal).toHaveAttribute('aria-pressed', 'true')
  await expect(vertical).toHaveAttribute('aria-pressed', 'true')
  await expect(constraints.getByRole('combobox', { name: 'Horizontal constraint' })).toContainText(
    'Center'
  )
  await expect(constraints.getByRole('combobox', { name: 'Vertical constraint' })).toContainText(
    'Center'
  )
  await constraints.screenshot({ path: testInfo.outputPath('constraints-center.png') })
})
